### 📍 본 노트북 내용은 인프런 강의 `파이썬(Python)으로 데이터 기반 주식 퀀트 투자하기 Part1`를 학습하고 정리한 내용임을 밝힙니다.

# 수업에 사용될 라이브러리 설치

In [ ]:
!ls   # 윈도우 사용자의 경우 -> dir 

In [ ]:
pip install numpy

In [ ]:
!pip install -r requirements.txt

# Numpy 소개

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

## ndarray dtype

numpy에서 array는 python의 list 역할과 유사하다.

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
# indexing이 list와 방식이 같음
a[0]

1

In [ ]:
a.

- append() 같은 함수가 없음 -> 즉, python의 list와는 다른 data type임

## Universal(vectorized) function

In [7]:
a = [1, 2, 3]
b = [4, 5, 6]

new_list = []
for e1, e2 in zip(a, b):
    new_list.append(e1 + e2)
new_list

[5, 7, 9]

In [8]:
a + b

[1, 2, 3, 4, 5, 6]

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [10]:
# 길이가 길어도 근사적으로 1초가 걸린다
a + b

array([5, 7, 9])

In [ ]:
# np.sum
# np.abs
# np.log
# np.exp
# np.isnan
# ...

- n차원 array

In [11]:
a = np.array([  [1, 2],  [3, 4]   ])
a

array([[1, 2],
       [3, 4]])

In [12]:
# readability 높이기
a = np.array(
    [
        [1, 2],
        [3, 4],
    ]
)

In [13]:
a[0][1]

2

In [14]:
a + a

array([[2, 4],
       [6, 8]])